name: CD
on:
  push:
    branches: [ "master" ]
    paths: ['.github/*', 'webapp/*']
  pull_request:
    branches: [ "master" ]
    paths: ['.github/*', 'webapp/*']
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: webapp
